pipeline
{
    agent any

    stages
    {
        stage('Dummy Setup')
        {
            steps
            {
                echo 'Dummy step says hello'
            }
        }
    }
    post
    {
        always
        {
            script
            {
                def GIT_LOG = sh ( script: 'git log --oneline --no-decorate $GIT_PREVIOUS_SUCCESSFUL_COMMIT..HEAD', returnStdout: true )
                def HOST_NAME = sh ( script: 'hostname', returnStdout: true )
                echo "$GIT_LOG"
                discordSend description: "$BUILD_URL",
                            footer: "$GIT_LOG",
                            image: '',
                            link: '',
                            result: currentBuild.currentResult,
                            thumbnail: '',
                            title: "$HOST_NAME: $JOB_NAME",
                            webhookURL: 'https://discordapp.com/api/webhooks/812735418504052766/AumZJU3Gt7fW0SsoigXsAp-xpAcPv5q2LGk6I41l8IJnfidxw-KbmESZamhmuy9B59aU'
            }
        }
    }
}


