// Example of running builds for the fruit axis, so the same steps should be carried out for
// apple, banana and orange.

// Uncomment the master node so that it orchestrates this job, however the matrix itself will use any agent.

// Note: if statements are used to make the banana 'build' unstable, and for the orange 'test' to fail, to demonstrate
// how failing stages appear in a matrix.

pipeline
{
    agent any //{ label 'Master' }

    stages
    {
        stage('Build & Test')
        {
            matrix
            {
                agent any   // Using "agent any" allows parallelisation across multiple executors & nodes
                axes
                {
                    axis
                    {
                        name 'FRUIT_AXIS'
                        values 'Apple', 'Banana', 'Orange'
                    }
                }
                stages
                {
                    stage('Build')
                    {
                        steps
                        {
                            echo "Do Test for ${FRUIT_AXIS}"
                            script
                            {
                                if ( "$env.FRUIT_AXIS" == 'Banana' )
                                {
                                    unstable 'Banana unstable'
                                }
                            }
                            sleep 10
                        }
                    }
                    stage('Test')
                    {
                        steps
                        {
                            echo "Do Test for ${FRUIT_AXIS}"
                            script
                            {
                                if ( "$env.FRUIT_AXIS" == 'Orange' )
                                {
                                    error 'Fail orange'
                                }
                            }
                            sleep 10
                        }
                    }
                }
            }
        }
    }
}