pipeline
{
    agent any

    stages
    {
        stage('Echo Nodes')
        {
            steps
            {
                script
                {
                    NODE_LIST = nodesByLabel label: 'Ubuntu'
                }
                echo "Node list: [ $NODE_LIST ]"
            }
        }
    }
}